CREATE TABLE loan (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    borrower_id BIGINT NOT NULL,
    principal_amount DECIMAL(15,2) NOT NULL,
    rate DECIMAL(5,2) NOT NULL,
    state VARCHAR(20) DEFAULT 'PROPOSED',
    maturity_date TIMESTAMP NOT NULL,
    invested_amount DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE loan_approval (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    loan_id BIGINT NOT NULL,
    approval_date TIMESTAMP NOT NULL,
    field_validator_employee_id BIGINT NOT NULL,
    field_validate_picture TEXT NOT NULL
);

CREATE TABLE investment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    loan_id BIGINT NOT NULL,
    investor_id BIGINT NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    expected_interest DECIMAL(15,2) NOT NULL,
    state VARCHAR(50) DEFAULT 'OPEN'
);

CREATE TABLE disbursement (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    loan_id BIGINT NOT NULL,
    disbursement_date TIMESTAMP NOT NULL,
    agreement_letter TEXT NOT NULL,
    field_officer_employee_id BIGINT NOT NULL
);